pipeline {
    agent any
    stages {
        stage('pulling') {
            steps {
                git credentialsId: 'api-gateway-service-id', url: 'git@github.com:abdabughazaleh/catalytic-api-gateway.git'
            }
        }
        stage('build') {
            steps {
                withMaven(maven: 'maven-3.8.6') {
                    bat 'mvn clean install'
                }
            }
        }
        stage("copy-service") {
            steps {
                bat 'xcopy /y "C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\deploy-api-gateway-service\\target\\api-gateway-0.0.1-SNAPSHOT.jar" "C:\\services\\api-gateway-0.0.1-SNAPSHOT.jar"'
            }
        }
        stage("create-service") {
            steps{
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    bat 'cmd /c C:\\Users\\Administrator\\Documents\\win64\\nssm.exe install api-gateway-service "C:\\Program Files\\Java\\jre1.8.0_202\\bin\\java.exe" "-jar C:\\services\\api-gateway-0.0.1-SNAPSHOT.jar"'
                }
            }
        }
        stage("install-react") {
            steps{
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    bat 'cmd /c npm install'
                }
            }
        }
        stage("build-react") {
            steps{
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    bat 'cmd /c npm build '
                }
            }
        }
        stage("start-react") {
            steps{
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    bat 'cmd /c npm build'
                }
            }
        }
        stage("stop-service") {
            steps{
                bat 'cmd /c C:\\Users\\Administrator\\Documents\\win64\\nssm.exe stop api-gateway-service'
            }
        }
        stage("start-service") {
            steps{
                bat 'cmd /c C:\\Users\\Administrator\\Documents\\win64\\nssm.exe start api-gateway-service'
            }
        }
    }
}