apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: eureka-server
  labels:
    app: eureka-server
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server-container
          image: abdabughazaleh/cat-price-eureka:latest
          imagePullPolicy: Always

      imagePullSecrets:
        - name: dockerauth
