pipeline {
    agent any
    stages {
        stage('Git Master Branch') {
            steps {
                git credentialsId: 'eureka-server-deploy', url: 'git@github.com:abdabughazaleh/eureka-server-cat.git'
            }
        }
        stage('Build') {
            steps {
                withMaven(maven: 'maven-3.8.6') {
                    bat 'mvn clean install'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                bat 'docker build -t abdabughazaleh/cat-price-eureka .'
            }
        }
        stage('Push Docker Image') {
            steps {
                withDockerRegistry([credentialsId: "docker_auth", url: "https://index.docker.io/v1/"]) {
                    bat "docker push abdabughazaleh/cat-price-eureka:latest"
                }
            }
        }
        stage('Run Service') {
            steps {
                bat 'kubectl apply -f=service.yaml'
            }
        }
        stage('Deploy To Test') {
            steps {
                script {
                    try {
                        bat 'kubectl apply -f=deployment.yaml'
                        bat 'kubectl rollout restart -f=deployment.yaml'
                    } catch (Exception e) {
                        e.printStackTrace()
                        bat 'kubectl apply -f=deployment.yaml'
                    }
                }
            }
        }
    }
}