apiVersion: v1
kind: Service
metadata:
  name: eureka-server-app
  labels:
    app: eureka-server-app
spec:
  selector:
    app: eureka-server
  ports:
    - port: 8761
      protocol: TCP
      targetPort: 8761
  type: LoadBalancer